(()=>{'use strict';const $=id=>document.getElementById(id),root=$('albumGrid');if(!root)return;
const issue=window.SUISHI_CONTENT?.entry?.id||'jianggao-001',api='/api/gallery?issue='+encodeURIComponent(issue);
const file=$('albumFiles'),feedback=$('albumFeedback'),count=$('albumCount'),drop=$('albumDropZone'),dialog=$('albumDialog');
let items=[],admin='',busy=false,previewUrl='';
const e=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const notify=s=>feedback.textContent=s;
async function req(method='GET',body){const h={};if(method!=='GET'){h['Content-Type']='application/json';h['X-Album-Admin']=admin}const r=await fetch(api,{method,headers:h,body:body?JSON.stringify(body):undefined,cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.error||'操作失败');return j}
const img=id=>api+'&image='+encodeURIComponent(id);
function draw(){count.textContent=items.length;root.innerHTML='';if(!items.length){root.innerHTML='<div class="album-empty">本期尚无照片。<br>上传一张照片，留住此刻。</div>';return}for(const p of items){const card=document.createElement('article');card.className='album-card';card.innerHTML='<button class="album-preview" type="button"><img loading="lazy" alt="'+e(p.caption||p.name)+'" src="'+img(p.id)+'"></button><div class="album-card-content"><p class="album-card-title">'+e(p.caption||p.name)+'</p><small>'+new Date(p.addedAt).toLocaleDateString('zh-CN')+'</small><div class="album-card-actions"><button data-act="edit" type="button">编辑说明</button><button data-act="delete" type="button">删除</button></div></div>';card.querySelector('.album-preview').onclick=()=>openPreview(p);card.querySelector('[data-act="edit"]').onclick=()=>change(p);card.querySelector('[data-act="delete"]').onclick=()=>remove(p);root.append(card)}}
async function load(){try{const j=await req();items=j.items||[];draw();notify('已从云端载入 '+items.length+' 张照片')}catch(err){notify('云端相册暂不可用：'+err.message)}}
function login(){const s=prompt('请输入相册管理员口令（不会保存在浏览器中）：');if(s===null)return false;admin=s;return !!s}
function canvas(file){return new Promise((resolve,reject)=>{const u=URL.createObjectURL(file),image=new Image();image.onload=()=>{URL.revokeObjectURL(u);try{const cv=document.createElement('canvas'),scale=Math.min(1,1600/Math.max(image.width,image.height));cv.width=Math.max(1,Math.round(image.width*scale));cv.height=Math.max(1,Math.round(image.height*scale));cv.getContext('2d').drawImage(image,0,0,cv.width,cv.height);cv.toBlob(b=>b?resolve(b):reject(Error('压缩失败')),'image/webp',.8)}catch(err){reject(err)}};image.onerror=()=>{URL.revokeObjectURL(u);reject(Error('不支持此图片'))};image.src=u})}
function b64(blob){return new Promise((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result).split(',')[1]);fr.onerror=()=>reject(Error('读取图片失败'));fr.readAsDataURL(blob)})}
async function upload(files){if(busy||!files.length)return;if(!admin&&!login())return;busy=true;let successful=0;try{for(const f of files){if(!['image/jpeg','image/png','image/webp','image/gif'].includes(f.type)||f.size>12*1024*1024){notify('请选用不超过12MB的常见图片格式');continue}try{const blob=await canvas(f);if(blob.size>1_800_000)throw Error('压缩后仍超过1.8MB');notify('正在上传 '+f.name+' …');await req('POST',{name:f.name,data:await b64(blob)});successful++}catch(err){notify('上传失败：'+err.message);if(/口令/.test(err.message))admin='';break}}await load();if(successful)notify('已上传 '+successful+' 张到 GitHub 私有仓库；网站公开展示可能需短暂等待。')}finally{busy=false;file.value=''}}
async function change(p){if(!admin&&!login())return;const caption=prompt('照片说明：',p.caption||'');if(caption===null)return;try{await req('PATCH',{id:p.id,caption:caption.trim().slice(0,80)});await load()}catch(err){notify('修改失败：'+err.message)}}
async function remove(p){if(!confirm('删除此照片？GitHub 历史提交中仍可能保留文件。'))return;if(!admin&&!login())return;try{await req('DELETE',{id:p.id});await load()}catch(err){notify('删除失败：'+err.message)}}
function openPreview(p){if(!dialog?.showModal)return;previewUrl=img(p.id);$('albumDialogImage').src=previewUrl;$('albumDialogCaption').textContent=p.caption||p.name;$('albumDialogMeta').textContent=new Date(p.addedAt).toLocaleDateString('zh-CN');const dl=$('albumDialogDownload');dl.href=previewUrl;dl.download='岁时家集-'+p.id+'.webp';dialog.showModal()}
file.addEventListener('change',()=>upload([...file.files]));for(const ev of ['dragenter','dragover'])drop.addEventListener(ev,x=>{x.preventDefault();drop.classList.add('drag-over')});for(const ev of ['dragleave','drop'])drop.addEventListener(ev,x=>{x.preventDefault();drop.classList.remove('drag-over')});drop.addEventListener('drop',ev=>{ev.preventDefault();upload([...ev.dataTransfer.files])});$('albumDialogClose').onclick=()=>dialog.close();dialog.addEventListener('click',ev=>{if(ev.target===dialog)dialog.close()});load();
})();