(()=>{'use strict';
const issueId=window.SUISHI_CONTENT?.entry?.id||'jianggao-001';
const DB_NAME='suishi-family-anthology-album',DB_VERSION=1,STORE='photos',MAX_COUNT=30,MAX_FILE=12*1024*1024;
const $=id=>document.getElementById(id);
const input=$('albumFiles'),drop=$('albumDropZone'),grid=$('albumGrid'),feed=$('albumFeedback'),counter=$('albumCount'),dialog=$('albumDialog');
if(!input||!drop||!grid)return;
let db=null,photos=[],displayUrls=[],modalUrl=null,busy=false;
const notify=(message)=>{feed.textContent=message};
function openDB(){return new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(Error('浏览器不支持 IndexedDB'));const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{let d=req.result;if(!d.objectStoreNames.contains(STORE)){let s=d.createObjectStore(STORE,{keyPath:'id'});s.createIndex('byIssue','issueId',{unique:false})}};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||Error('数据库打开失败'));req.onblocked=()=>reject(Error('数据库被其他标签页占用'))})}
function transaction(kind,action){return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,kind),s=tx.objectStore(STORE);let value;try{value=action(s,tx)}catch(e){reject(e);return}tx.oncomplete=()=>resolve(value);tx.onerror=()=>reject(tx.error||Error('本地存储失败'));tx.onabort=()=>reject(tx.error||Error('操作已取消'))})}
function fetchPhotos(){return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),request=tx.objectStore(STORE).index('byIssue').getAll(IDBKeyRange.only(issueId));request.onsuccess=()=>resolve(request.result||[]);request.onerror=()=>reject(request.error||Error('读取相册失败'))})}
function storePhoto(photo){return transaction('readwrite',s=>s.put(photo))}
function deletePhoto(id){return transaction('readwrite',s=>s.delete(id))}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function clearUrls(){displayUrls.forEach(URL.revokeObjectURL);displayUrls=[]}
function formatDate(iso){return new Date(iso).toLocaleDateString('zh-CN',{year:'numeric',month:'short',day:'numeric'})}
function render(){clearUrls();photos.sort((a,b)=>b.addedAt.localeCompare(a.addedAt));counter.textContent=String(photos.length);if(!photos.length){grid.innerHTML='<div class="album-empty">本期影像簿尚未收录照片。<br>择一帧此刻，让时光有迹可循。</div>';return}grid.innerHTML='';for(const p of photos){const u=URL.createObjectURL(p.blob);displayUrls.push(u);const article=document.createElement('article');article.className='album-card';article.innerHTML='<button type="button" class="album-preview" aria-label="预览 '+escapeHtml(p.caption||p.name)+'"><img alt="'+escapeHtml(p.caption||'江皋携女记本期照片')+'" loading="lazy"></button><div class="album-card-content"><div class="album-card-top"><p class="album-card-title" title="'+escapeHtml(p.caption||p.name)+'">'+escapeHtml(p.caption||p.name)+'</p><time datetime="'+escapeHtml(p.addedAt)+'">'+formatDate(p.addedAt)+'</time></div><div class="album-card-actions"><button type="button" data-action="caption">添加／修改说明</button><button type="button" data-action="delete">删除</button></div></div>';article.querySelector('img').src=u;article.querySelector('.album-preview').onclick=()=>preview(p);article.querySelector('[data-action="caption"]').onclick=()=>editCaption(p);article.querySelector('[data-action="delete"]').onclick=()=>remove(p);grid.append(article)}}
function preview(p){if(!dialog||typeof dialog.showModal!=='function'){notify('当前浏览器不支持弹窗预览');return}if(modalUrl)URL.revokeObjectURL(modalUrl);modalUrl=URL.createObjectURL(p.blob);$('albumDialogImage').src=modalUrl;$('albumDialogImage').alt=p.caption||p.name;$('albumDialogCaption').textContent=p.caption||p.name;$('albumDialogMeta').textContent='本期相册 · '+formatDate(p.addedAt);const a=$('albumDialogDownload');a.href=modalUrl;a.download=p.name.replace(/\.[^.]+$/, '')+'-岁时家集.'+(p.blob.type==='image/png'?'png':p.blob.type==='image/gif'?'gif':p.blob.type==='image/webp'?'webp':'jpg');dialog.showModal()}
async function editCaption(p){const result=prompt('照片说明（最多 80 字）：',p.caption||'');if(result===null)return;const next=result.trim().slice(0,80);try{await storePhoto({...p,caption:next});await refresh();notify('照片说明已保存到本机浏览器')}catch(e){notify('说明保存失败：'+e.message)}}
async function remove(p){if(!confirm('确定删除这张照片吗？此操作无法恢复。'))return;try{await deletePhoto(p.id);await refresh();notify('照片已从当前浏览器删除')}catch(e){notify('删除失败：'+e.message)}}
function compress(file){if(file.type==='image/gif')return Promise.resolve(file);return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);try{const ratio=Math.min(1,1920/Math.max(img.naturalWidth,img.naturalHeight));const cvs=document.createElement('canvas');cvs.width=Math.max(1,Math.round(img.naturalWidth*ratio));cvs.height=Math.max(1,Math.round(img.naturalHeight*ratio));const ctx=cvs.getContext('2d');if(!ctx)throw Error('浏览器无法处理图片');ctx.drawImage(img,0,0,cvs.width,cvs.height);cvs.toBlob(blob=>blob?resolve(blob):reject(Error('照片压缩失败')),'image/webp',0.83)}catch(e){reject(e)}};img.onerror=()=>{URL.revokeObjectURL(url);reject(Error('无法读取这张图片，请换成 JPEG、PNG、WebP 或 GIF'))};img.src=url})}
async function refresh(){photos=await fetchPhotos();render()}
async function addFiles(fileList){if(!db){notify('本机相册不可用，照片不会被保存');return}if(busy)return;busy=true;const files=[...fileList];let ok=0,failed=[];try{for(const file of files){if(photos.length>=MAX_COUNT){failed.push('已达到每期 30 张上限');break}if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type)){failed.push(file.name+' 格式不支持');continue}if(file.size>MAX_FILE){failed.push(file.name+' 超过 12MB');continue}try{const blob=await compress(file);const p={id:(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random()),issueId,name:file.name,blob,caption:'',addedAt:new Date().toISOString()};await storePhoto(p);photos.push(p);ok++}catch(e){failed.push(file.name+' 保存失败：'+e.message)}}await refresh();notify((ok?('成功保存 '+ok+' 张照片到当前浏览器。'):'未保存新照片。')+(failed.length?' '+failed.slice(0,2).join('；')+(failed.length>2?' 等 '+failed.length+' 个问题':''):'')+(ok?' 请备份重要原图。':''))}finally{input.value='';busy=false}}
input.addEventListener('change',()=>addFiles(input.files));for(const evt of ['dragenter','dragover'])drop.addEventListener(evt,e=>{e.preventDefault();drop.classList.add('drag-over')});for(const evt of ['dragleave','drop'])drop.addEventListener(evt,e=>{e.preventDefault();drop.classList.remove('drag-over')});drop.addEventListener('drop',e=>{if(e.dataTransfer?.files?.length)addFiles(e.dataTransfer.files)});
$('albumDialogClose').onclick=()=>dialog.close();dialog.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});dialog.addEventListener('close',()=>{if(modalUrl)URL.revokeObjectURL(modalUrl);modalUrl=null;$('albumDialogImage').removeAttribute('src')});
async function init(){try{db=await openDB();await refresh();notify('相册已就绪 · 当前浏览器本地保存')}catch(e){notify('无法开启本地相册：'+e.message+'；请使用非无痕模式并确认浏览器允许本地存储。');drop.hidden=true}}
init();window.addEventListener('pagehide',()=>{clearUrls();if(modalUrl)URL.revokeObjectURL(modalUrl)})})();